[package]
name = "enc"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
k256 = { version = "0.13.4", features = ["ecdh"] }
zeroize = { version = "1.8.1", features = ["derive"] }
